In [1]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code

### list_ : This is a simple list
### array_list : is a numpy an array which will have dimension

In [2]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
# Print the data type of each element in the list
for element in list_:
    print("Data type of element in list_:", type(element))

# Print the data type of each element in the NumPy array
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list. 

In [4]:
import numpy as np

list_ = ["1", "2", "3", "4", "5"]
array_list = np.array(list_, dtype=int)

# Print the data type of each element in the list
for element in list_:
    print("Data type of element in list_:", type(element))

# Print the data type of each element in the NumPy array
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


# Consider the below code to answer further questions: import numpy as np num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:


In [6]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Find shape of num_array
print("Shape of num_array:", num_array.shape)

# Find size of num_array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [7]:
import numpy as np

# Create 3x3 numpy array containing zeros
zeros_array = np.zeros((3, 3))

# Print the zeros array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print(identity_matrix)